SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# player
PLAYER_RADIUS = 20
SHOT_RADIUS = 5

# drawing
LINE_WIDTH = 2

#rotation
PLAYER_TURN_SPEED = 300

#speed
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

# asteroids
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPEED_UP_FACTOR = 1.2